# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '10.0'
    use_frameworks!

target 'GoldPrice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoldPrice


    pod 'Alamofire', '~> 4.5'




  target 'GoldPriceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoldPriceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
